# Generated by Django 5.2.17 on 2026-09-14 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên khu vực')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Khu vực',
                'verbose_name_plural': 'Khu vực',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên bàn')),
                ('code', models.CharField(max_length=30, verbose_name='Mã bàn')),
                ('capacity', models.PositiveSmallIntegerField(default=4, verbose_name='Số chỗ')),
                ('status', models.CharField(choices=[('available', 'Trống'), ('occupied', 'Đang phục vụ'), ('reserved', 'Đã đặt'), ('maintenance', 'Bảo trì')], default='available', max_length=20, verbose_name='Trạng thái')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='dining.area', verbose_name='Khu vực')),
            ],
            options={
                'verbose_name': 'Bàn',
                'verbose_name_plural': 'Bàn',
                'ordering': ('area__display_order', 'display_order', 'name'),
                'indexes': [models.Index(fields=['area', 'status', 'is_active'], name='dining_dini_area_id_587f91_idx')],
                'constraints': [models.UniqueConstraint(fields=('area', 'name'), name='unique_table_name_per_area')],
            },
        ),
    ]
