# Generated by Django 5.2.17 on 2026-09-15 16:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recipe', to='catalog.product', verbose_name='Món ăn')),
            ],
            options={
                'verbose_name': 'Công thức món',
                'verbose_name_plural': 'Công thức món',
            },
        ),
        migrations.CreateModel(
            name='StockReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_code', models.CharField(max_length=30, unique=True, verbose_name='Mã phiếu nhập')),
                ('supplier', models.CharField(blank=True, max_length=150, verbose_name='Nhà cung cấp')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tổng tiền')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('confirmed', 'Đã nhập kho'), ('cancelled', 'Đã hủy')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phiếu nhập kho',
                'verbose_name_plural': 'Phiếu nhập kho',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StockReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Số lượng')),
                ('unit_cost', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Đơn giá nhập')),
                ('total_cost', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Thành tiền')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='catalog.ingredient')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockreceipt')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Định lượng')),
                ('unit', models.CharField(max_length=30, verbose_name='Đơn vị')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_items', to='catalog.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.recipe')),
            ],
            options={
                'verbose_name': 'Nguyên liệu trong công thức',
                'verbose_name_plural': 'Nguyên liệu trong công thức',
                'constraints': [models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_ingredient_per_recipe')],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('receipt', 'Nhập kho'), ('sale', 'Xuất kho bán hàng'), ('issue', 'Xuất kho thủ công'), ('increase', 'Điều chỉnh tăng'), ('decrease', 'Điều chỉnh giảm')], max_length=20, verbose_name='Loại giao dịch')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Số lượng biến động')),
                ('unit_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Đơn giá vốn')),
                ('balance_after', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Tồn sau giao dịch')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='Loại tham chiếu')),
                ('reference_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='catalog.ingredient')),
            ],
            options={
                'verbose_name': 'Biến động kho',
                'verbose_name_plural': 'Biến động kho',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['ingredient', 'created_at'], name='inventory_s_ingredi_15577e_idx'), models.Index(fields=['transaction_type', 'created_at'], name='inventory_s_transac_fce13a_idx')],
            },
        ),
    ]
