# Generated by Django 5.2.17 on 2026-09-15 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Thêm mới'), ('update', 'Cập nhật'), ('delete', 'Xóa/Ngừng dùng'), ('payment', 'Thanh toán'), ('login', 'Đăng nhập'), ('other', 'Khác')], default='other', max_length=20, verbose_name='Hoạt động')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='HTTP method')),
                ('path', models.CharField(max_length=255, verbose_name='Đường dẫn')),
                ('object_type', models.CharField(blank=True, max_length=100, verbose_name='Loại đối tượng')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=500, verbose_name='Chi tiết')),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lịch sử hoạt động',
                'verbose_name_plural': 'Lịch sử hoạt động',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['created_at', 'action'], name='audit_activ_created_ac0117_idx'), models.Index(fields=['actor', 'created_at'], name='audit_activ_actor_i_5122be_idx')],
            },
        ),
    ]
