# Generated by Django 5.2.17 on 2026-09-14 16:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên danh mục')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('color', models.CharField(default='#f5c92c', max_length=20, verbose_name='Màu hiển thị')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Danh mục món',
                'verbose_name_plural': 'Danh mục món',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Mã nguyên liệu')),
                ('name', models.CharField(max_length=150, verbose_name='Tên nguyên liệu')),
                ('unit', models.CharField(default='Kg', max_length=30, verbose_name='Đơn vị tính')),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tồn hiện tại')),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tồn tối thiểu')),
                ('average_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá vốn bình quân')),
                ('supplier', models.CharField(blank=True, max_length=150, verbose_name='Nhà cung cấp')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nguyên liệu',
                'verbose_name_plural': 'Nguyên liệu',
                'ordering': ('name',),
                'indexes': [models.Index(fields=['name', 'is_active'], name='catalog_ing_name_ac323a_idx'), models.Index(fields=['current_stock', 'minimum_stock'], name='catalog_ing_current_785062_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Mã món')),
                ('name', models.CharField(max_length=150, verbose_name='Tên món')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('unit', models.CharField(default='Phần', max_length=30, verbose_name='Đơn vị tính')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Đơn giá')),
                ('price_2', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Đơn giá 2')),
                ('price_3', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Đơn giá 3')),
                ('cost_price', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá vốn')),
                ('product_type', models.CharField(choices=[('food', 'Món ăn'), ('drink', 'Đồ uống'), ('topping', 'Topping'), ('other', 'Khác')], default='food', max_length=20, verbose_name='Loại món')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Ảnh món')),
                ('is_available', models.BooleanField(default=True, verbose_name='Đang bán')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Món ăn',
                'verbose_name_plural': 'Món ăn',
                'ordering': ('category__display_order', 'name'),
                'indexes': [models.Index(fields=['name', 'is_active'], name='catalog_pro_name_c2035e_idx'), models.Index(fields=['category', 'is_active'], name='catalog_pro_categor_891fe8_idx')],
            },
        ),
    ]
