# Generated by Django 5.2.17 on 2026-10-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subgroup',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nhóm con'),
        ),
    ]
