# Generated by Django 5.2.17 on 2026-10-03 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Đang mở'), ('closed', 'Đã kết')], default='open', max_length=10, verbose_name='Trạng thái')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_shifts', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ca làm việc',
                'verbose_name_plural': 'Ca làm việc',
                'ordering': ('-started_at',),
            },
        ),
    ]
